//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildberriesParser.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectorTask
    {
        public int ID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Name { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string TaskDetails { get; set; }
    
        public virtual User User { get; set; }
        public virtual CollectorTaskStatus CollectorTaskStatus { get; set; }
        public virtual CollectorTaskType CollectorTaskType { get; set; }
    }
}
