//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildberriesParser.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WbProductSales
    {
        public int WbProductID { get; set; }
        public System.DateTime Date { get; set; }
        public int Sales { get; set; }
        public int Price { get; set; }
    
        public virtual WbProduct WbProduct { get; set; }
    }
}
